------------------ ΠΡΟΣΟΧΗ ΠΡΟΣΟΧΗ ΠΡΟΣΟΧΗ 
------ ΕΛΕΓΧΟΣ ΥΠΑΡΞΗΣ ΚΑΤΗΓΟΡΙΑΣ ΣΤΟΝ Z_CUSTOMER_CATEGORY_EMPPOL_NEW

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--DROP TABLE Z_EP_N1_B2B 
DELETE FROM Z_EP_N1_B2B 
--CREATE TABLE Z_EP_N1_B2B  (ID uniqueidentifier, TRDRID VARCHAR(255),CUSTID VARCHAR(255),CUSTCODE VARCHAR(255),ITEMID VARCHAR(255),DISCOUNT1 INT)
INSERT INTO Z_EP_N1_B2B  (ID,TRDRID,CUSTID,CUSTCODE,itemid,DISCOUNT1)
select newid(),
CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXTRDRID )TRDRID,
CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXID ) CUSTID,
Z_CUSTOMER_CATEGORY_EMPPOL_NEW.CUSTCODE CUSTCODE,
CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL.itemid)ITEMID,
case GXCPEFFECTDASSIGN.GXDISCKIND when 1 then CAST(GXCPEFFECTDASSIGN.GXVALUE AS NUMERIC(12,2) ) else 0 end [ΠΟΣΟΣΤΟ ΕΚΤΩΣΗΣ]
from GXCPOLICY
inner join GXCPOLICYLINES on GXCPOLICY.GXID = GXCPOLICYLINES.GXCPOLID
inner join GXCPCONDITIONTERM on GXCPOLICYLINES.GXCPTEID = GXCPCONDITIONTERM.GXID
inner join GXCPCONDITIONTYPE on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,20,36) )= CONVERT(uniqueidentifier,GXCPCONDITIONTYPE.gxid)
inner join gxCPCondTypeObjects on CONVERT(uniqueidentifier,GXCPCONDITIONTYPE.GXID) = CONVERT(uniqueidentifier,gxCPCondTypeObjects.GXCPCTID)
INNER JOIN Z_CUSTOMER_CATEGORY_EMPPOL_NEW ON CONVERT(uniqueidentifier,gxCPCondTypeObjects.GXOBJECTID) = CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.catid)
inner join GXCPCONDITIONTYPE GXCPCONDITIONTYPE2 on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,81,36) )= CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.gxid)
inner join gxCPCondTypeObjects gxCPCondTypeObjects2 on CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.GXID) = CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXCPCTID)
INNER JOIN Z_ITEM_CATEGORY_EMP_POL  ON CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXOBJECTID) = CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL.GXID) AND gxCPCondTypeObjects2.GXOBJECTID IS NOT NULL AND gxCPCondTypeObjects2.GXSECOBJECTID IS NOT NULL
inner join GXCPOLICYLINEEFFECTS on CONVERT(uniqueidentifier,GXCPOLICYLINES.GXID) = CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPLNID)
inner join GXCPEFFECT on CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPEFID) = CONVERT(uniqueidentifier,GXCPEFFECT.GXID)
Inner join GXCPEFFECTDASSIGN on CONVERT(uniqueidentifier,GXCPEFFECT.GXID) = CONVERT(uniqueidentifier,GXCPEFFECTDASSIGN.GXCPEFID)
where 
GXCOMPOLTYPE = 1 
and gxcpolicy.gxcode LIKE '21%'
and GXCPEFFECTDASSIGN.GXEXECORDER = 1
AND GXCPOLICY.GXACTIVE = 1 
and Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXBOOLEANFIELD1 = 1 
--DROP TABLE Z_EP_N2_B2B

---------------   ΘΕΜΕΛΗΣ CONTI GROUP DISCOUNT-----------------
INSERT INTO Z_EP_N1_B2B  (ID,TRDRID,CUSTID,CUSTCODE,itemid,DISCOUNT1)
select 
newid(),
(select gxid from gxtrader where gxtrader.GXCODE = '03041'),
(select gxid from GXCUSTOMER where GXCUSTOMER.GXCODE = '1-18-0002'),
'1-18-0002',
Z_ITEM_CATEGORY_EMP_POL_conti_g_pass.itemid,
case GXCPEFFECTDASSIGN.GXDISCKIND when 1 then CAST(GXCPEFFECTDASSIGN.GXVALUE AS NUMERIC(12,2) ) else 0 end 
from GXCPOLICY
inner join GXCPOLICYLINES on GXCPOLICY.GXID = GXCPOLICYLINES.GXCPOLID
inner join GXCPCONDITIONTERM on GXCPOLICYLINES.GXCPTEID = GXCPCONDITIONTERM.GXID
inner join GXCPCONDITIONTYPE GXCPCONDITIONTYPE2 on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,20,36) )= CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.gxid)
inner join gxCPCondTypeObjects gxCPCondTypeObjects2 on CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.GXID) = CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXCPCTID)
left JOIN Z_ITEM_CATEGORY_EMP_POL_conti_g_pass  ON CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXOBJECTID) = CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL_conti_g_pass.GXID) AND gxCPCondTypeObjects2.GXOBJECTID IS NOT NULL AND gxCPCondTypeObjects2.GXSECOBJECTID IS NOT NULL
inner join GXCPOLICYLINEEFFECTS on CONVERT(uniqueidentifier,GXCPOLICYLINES.GXID) = CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPLNID)
inner join GXCPEFFECT on CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPEFID) = CONVERT(uniqueidentifier,GXCPEFFECT.GXID)
Inner join GXCPEFFECTDASSIGN on CONVERT(uniqueidentifier,GXCPEFFECT.GXID) = CONVERT(uniqueidentifier,GXCPEFFECTDASSIGN.GXCPEFID)
where 
GXCOMPOLTYPE = 1 
and gxcpolicy.gxcode LIKE 'ΘΕΜ CONTI GROUP'
and GXCPEFFECTDASSIGN.GXEXECORDER = 1
AND GXCPOLICY.GXACTIVE = 1 




DELETE FROM Z_EP_N2_B2B 
--CREATE TABLE Z_EP_N2_B2B (TRDRID VARCHAR(255),CUSTID VARCHAR(255), CUSTCODE VARCHAR(255),ITEMID VARCHAR(255),DISCOUNT2 INT)
INSERT INTO Z_EP_N2_B2B 
select 
newid(),
CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXTRDRID )TRDRID,
CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXID )CUSTID,
Z_CUSTOMER_CATEGORY_EMPPOL_NEW.CUSTCODE CUSTCODE,
CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL.itemid )ITEMID  ,
case GXCPEFFECTDASSIGN.GXDISCKIND when 1 then CAST(GXCPEFFECTDASSIGN.GXVALUE AS NUMERIC(12,2) ) else 0 end [ΠΟΣΟΣΤΟ ΕΚΤΩΣΗΣ]
from GXCPOLICY
inner join GXCPOLICYLINES on CONVERT(uniqueidentifier,GXCPOLICY.GXID )= CONVERT(uniqueidentifier,GXCPOLICYLINES.GXCPOLID)
inner join GXCPCONDITIONTERM on CONVERT(uniqueidentifier,GXCPOLICYLINES.GXCPTEID )= CONVERT(uniqueidentifier,GXCPCONDITIONTERM.GXID)
inner join GXCPCONDITIONTYPE on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,20,36) )= CONVERT(uniqueidentifier,GXCPCONDITIONTYPE.gxid)
inner join gxCPCondTypeObjects on CONVERT(uniqueidentifier,GXCPCONDITIONTYPE.GXID )= CONVERT(uniqueidentifier,gxCPCondTypeObjects.GXCPCTID)
INNER JOIN Z_CUSTOMER_CATEGORY_EMPPOL_NEW ON CONVERT(uniqueidentifier,gxCPCondTypeObjects.GXOBJECTID )= CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.catid)
inner join GXCPCONDITIONTYPE GXCPCONDITIONTYPE2 on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,81,36) )= CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.gxid)
inner join gxCPCondTypeObjects gxCPCondTypeObjects2 on CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.GXID )= CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXCPCTID)
INNER JOIN Z_ITEM_CATEGORY_EMP_POL  ON CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXOBJECTID )= 
CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL.GXID )AND CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXOBJECTID )IS NOT NULL AND CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXSECOBJECTID )IS NOT NULL
inner join GXCPOLICYLINEEFFECTS on CONVERT(uniqueidentifier,GXCPOLICYLINES.GXID )= CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPLNID)
inner join GXCPEFFECT on CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPEFID )= CONVERT(uniqueidentifier,GXCPEFFECT.GXID)
Inner join GXCPEFFECTDASSIGN on CONVERT(uniqueidentifier,GXCPEFFECT.GXID) = CONVERT(uniqueidentifier,GXCPEFFECTDASSIGN.GXCPEFID)
where 
GXCOMPOLTYPE = 1 
and gxcpolicy.gxcode LIKE '21%'
and GXCPEFFECTDASSIGN.GXEXECORDER = 2
AND GXCPOLICY.GXACTIVE = 1 
AND Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXBOOLEANFIELD1 = 1 
and GXCPOLICYLINES.GXACTIVE = 1 
--drop table Z_EP_AX_B2B
--CREATE TABLE Z_EP_AX_B2B (ITEMID UNIQUEIDENTIFIER,DISCAX decimal(10,2))

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
----DROP TABLE Z_EP_N1_B2B 

--DELETE FROM Z_EP_N3_B2B 
----CREATE TABLE Z_EP_N1_B2B  (ID uniqueidentifier, TRDRID VARCHAR(255),CUSTID VARCHAR(255),CUSTCODE VARCHAR(255),ITEMID VARCHAR(255),DISCOUNT1 INT)
--INSERT INTO Z_EP_N3_B2B  (ID,TRDRID,CUSTID,CUSTCODE,itemid,DISCOUNT3)
--select newid(),
--CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXTRDRID )TRDRID,
--CONVERT(uniqueidentifier,Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXID ) CUSTID,
--Z_CUSTOMER_CATEGORY_EMPPOL_NEW.CUSTCODE CUSTCODE,
--CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL.itemid) ITEMID,
--case GXCPEFFECTDASSIGN.GXDISCKIND when 1 then CAST(GXCPEFFECTDASSIGN.GXVALUE AS NUMERIC(12,2) ) else 0 end [ΠΟΣΟΣΤΟ ΕΚΤΩΣΗΣ]
--from GXCPOLICY
--inner join GXCPOLICYLINES on GXCPOLICY.GXID = GXCPOLICYLINES.GXCPOLID
--inner join GXCPCONDITIONTERM on GXCPOLICYLINES.GXCPTEID = GXCPCONDITIONTERM.GXID
--inner join GXCPCONDITIONTYPE on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,20,36) )= GXCPCONDITIONTYPE.gxid
--inner join gxCPCondTypeObjects on GXCPCONDITIONTYPE.GXID = gxCPCondTypeObjects.GXCPCTID
--INNER JOIN Z_CUSTOMER_CATEGORY_EMPPOL_NEW ON gxCPCondTypeObjects.GXOBJECTID = Z_CUSTOMER_CATEGORY_EMPPOL_NEW.catid
--inner join GXCPCONDITIONTYPE GXCPCONDITIONTYPE2 on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,81,36) )= GXCPCONDITIONTYPE2.gxid
--inner join gxCPCondTypeObjects gxCPCondTypeObjects2 on GXCPCONDITIONTYPE2.GXID = gxCPCondTypeObjects2.GXCPCTID

--INNER JOIN Z_ITEM_CATEGORY_EMP_POL  ON gxCPCondTypeObjects2.GXOBJECTID = Z_ITEM_CATEGORY_EMP_POL.GXID AND gxCPCondTypeObjects2.GXOBJECTID IS NOT NULL AND gxCPCondTypeObjects2.GXSECOBJECTID IS NOT NULL

--inner join GXCPOLICYLINEEFFECTS on GXCPOLICYLINES.GXID = GXCPOLICYLINEEFFECTS.GXCPLNID
--inner join GXCPEFFECT on GXCPOLICYLINEEFFECTS.GXCPEFID = GXCPEFFECT.GXID
--Inner join GXCPEFFECTDASSIGN on GXCPEFFECT.GXID = GXCPEFFECTDASSIGN.GXCPEFID
--where 
--GXCOMPOLTYPE = 1 
--and gxcpolicy.gxcode LIKE  '21%'
--and GXCPEFFECTDASSIGN.GXEXECORDER = 3
--AND GXCPOLICY.GXACTIVE = 1 
--and Z_CUSTOMER_CATEGORY_EMPPOL_NEW.GXBOOLEANFIELD1 = 1 
delete from Z_EP_AX_B2B 
insert into Z_EP_AX_B2B 
select distinct
CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL.itemid )ITEMID  ,
case GXCPEFFECTDASSIGN.GXDISCKIND when 2 then ISNULL(CAST(SUBSTRING(GXCPEFFECTDASSIGN.GXFORMULA,8,10) AS NUMERIC(12,2)),0) else 0 end [ΑΞΙΑΚΗ ΕΚΠΤΩΣΗ]
from GXCPOLICY
inner join GXCPOLICYLINES on CONVERT(uniqueidentifier,GXCPOLICY.GXID )= CONVERT(uniqueidentifier,GXCPOLICYLINES.GXCPOLID)
inner join GXCPCONDITIONTERM on CONVERT(uniqueidentifier,GXCPOLICYLINES.GXCPTEID )= CONVERT(uniqueidentifier,GXCPCONDITIONTERM.GXID)
inner join GXCPCONDITIONTYPE on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,20,36) )= CONVERT(uniqueidentifier,GXCPCONDITIONTYPE.gxid)
inner join gxCPCondTypeObjects on CONVERT(uniqueidentifier,GXCPCONDITIONTYPE.GXID )= CONVERT(uniqueidentifier,gxCPCondTypeObjects.GXCPCTID)
left outer JOIN Z_CUSTOMER_CATEGORY_GENIKH_NEW ON CONVERT(uniqueidentifier,gxCPCondTypeObjects.GXOBJECTID )= CONVERT(uniqueidentifier,z_CUSTOMER_CATEGORY_GENIKH_NEW.GXID)
inner join GXCPCONDITIONTYPE GXCPCONDITIONTYPE2 on CONVERT(uniqueidentifier,substring(GXCPCONDITIONTERM.GXCONDITIONFILTER,81,36) )= CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.gxid)
inner join gxCPCondTypeObjects gxCPCondTypeObjects2 on CONVERT(uniqueidentifier,GXCPCONDITIONTYPE2.GXID) = CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXCPCTID)
INNER JOIN Z_ITEM_CATEGORY_EMP_POL  ON CONVERT(uniqueidentifier,gxCPCondTypeObjects2.GXOBJECTID )= CONVERT(uniqueidentifier,Z_ITEM_CATEGORY_EMP_POL.GXID)
inner join GXCPOLICYLINEEFFECTS on CONVERT(uniqueidentifier,GXCPOLICYLINES.GXID )= CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPLNID)
inner join GXCPEFFECT on CONVERT(uniqueidentifier,GXCPOLICYLINEEFFECTS.GXCPEFID )= CONVERT(uniqueidentifier,GXCPEFFECT.GXID)
Inner join GXCPEFFECTDASSIGN on CONVERT(uniqueidentifier,GXCPEFFECT.GXID )= CONVERT(uniqueidentifier,GXCPEFFECTDASSIGN.GXCPEFID)
where 
GXCOMPOLTYPE = 1 
and (gxcpolicy.gxcode in  ('MICHELIN 19 3Ε','ΕΥΡΩ' ))
and getdate() between GXCPOLICYLINES.GXDATEFROM and GXCPOLICYLINES.GXDATETO
AND GXCPOLICY.GXACTIVE = 1 

DELETE Z_ITEM_SEARCH_DIASTASI 
INSERT INTO Z_ITEM_SEARCH_DIASTASI(ID,ITEMID,DIASTASI)  
select
LEFT(gxitem.gxid,28)+LEFT(gxitem.gxid,8)  ID, 
gxitem.gxid ITEMID,

case 
WHEN Z_ITEM_ATTRIB_KATASKEVASTIS.ATTRVALUE  LIKE 'TATKO%' AND Z_ITEM_ATTRIB_GROUP.GXDESCRIPTION = 'ΑΓΡΟΤΙΚΟ'
THEN REPLACE(Z_ITEM_ATTRIB_FARDOS.ATTRVALUE,'.','') + isnull(replace(Z_ITEM_ATTRIB_SEIRA.ATTRVALUE,'-',''),'') +  isnull(replace(Z_ITEM_ATTRIB_ZANTA.ATTRVALUE,'.',''),'') 
WHEN Z_ITEM_ATTRIB_KATASKEVASTIS.ATTRVALUE  LIKE 'TATKO%' AND Z_ITEM_ATTRIB_GROUP.GXDESCRIPTION = 'ΒΙΟΜΗΧΑΝΙΚΟ' 
then REPLACE(Z_ITEM_ATTRIB_FARDOS.ATTRVALUE,'.','')  + isnull(replace(Z_ITEM_ATTRIB_SEIRA.ATTRVALUE,'-',''),'') + REPLACE(Z_ITEM_ATTRIB_ZANTA.ATTRVALUE,'.','')

when Z_ITEM_ATTRIB_SEIRA.ATTRVALUE = '-' OR  Z_ITEM_ATTRIB_SEIRA.ATTRVALUE  IS NULL  or Z_ITEM_ATTRIB_SEIRA.ATTRVALUE = '.' then replace(Z_ITEM_ATTRIB_FARDOS.ATTRVALUE,'.','') + replace(Z_ITEM_ATTRIB_ZANTA.ATTRVALUE,'.','')
else replace(Z_ITEM_ATTRIB_FARDOS.ATTRVALUE,'.','')  + replace(Z_ITEM_ATTRIB_SEIRA.ATTRVALUE,'.','')   + replace(Z_ITEM_ATTRIB_ZANTA.ATTRVALUE,'.','') 

end DIASTASI
--,
--GXITEM.GXDESCRIPTION,Z_ITEM_ATTRIB_GROUP.GXDESCRIPTION
--Z_ITEM_ATTRIB_SEIRA.ATTRVALUE SEIRA ,
--Z_ITEM_ATTRIB_FARDOS.ATTRVALUE FARDOS,
--Z_ITEM_ATTRIB_ZANTA.ATTRVALUE ZANTA
from
GXITEM
left join Z_ITEM_ATTRIB_SEIRA  on Z_ITEM_ATTRIB_SEIRA.ENTITYCODE = GXITEM.GXCODE
left join Z_ITEM_ATTRIB_FARDOS on Z_ITEM_ATTRIB_FARDOS.ENTITYCODE = GXITEM.GXCODE
left join Z_ITEM_ATTRIB_ZANTA on Z_ITEM_ATTRIB_ZANTA.ENTITYCODE = GXITEM.GXCODE
LEFT JOIN Z_ITEM_ATTRIB_KATASKEVASTIS ON Z_ITEM_ATTRIB_KATASKEVASTIS.itemid = GXITEM.GXID
LEFT JOIN Z_ITEM_ATTRIB_GROUP ON Z_ITEM_ATTRIB_GROUP.CODE = GXITEM.GXCODE
--where gxitem.gxcode   = '0373218'

delete Z_ITEM_SEARCH_DIASTASI where Z_ITEM_SEARCH_DIASTASI.ITEMID = '91C6F8F1-6BC5-4C98-F5B1-01759CBA6BFF'
insert into Z_ITEM_SEARCH_DIASTASI values (newid(),'91C6F8F1-6BC5-4C98-F5B1-01759CBA6BFF','12580')
INSERT INTO Z_ITEM_SEARCH_DIASTASI(ID,ITEMID,DIASTASI)  
select LEFT(DYDIASTASI.DYID,28)+LEFT(DYDIASTASI.DYID,8)  ID, DYDIASTASI.GXITEMID, DYDIASTASI.DYXDIASTAS  from DYDIASTASI

update Z_ITEM_SEARCH_DIASTASI set Z_ITEM_SEARCH_DIASTASI.DIASTASI = replace(Z_ITEM_SEARCH_DIASTASI.DIASTASI,'"','') where Z_ITEM_SEARCH_DIASTASI.DIASTASI like '%"%'

DELETE Z_ITEM_ISFORA_ANA_TEMAXIO_TBL 
INSERT INTO Z_ITEM_ISFORA_ANA_TEMAXIO_TBL 

SELECT        dbo.GXITEM.GXCODE, dbo.GXMASTERCAT.GXDESCRIPTION, AVG(SUBSTRING(dbo.GXFINACCOUNT.GXFORMULA, 12, 4) * (1.24) /(1.24)) AS ISFORA
FROM            dbo.GXFIACITEMCAT INNER JOIN
                         dbo.GXFINACCOUNT ON dbo.GXFIACITEMCAT.GXFIACID = dbo.GXFINACCOUNT.GXID INNER JOIN
                         dbo.GXITEMCATEGORY ON dbo.GXFIACITEMCAT.GXMSCTIDLEAF = dbo.GXITEMCATEGORY.GXMSCTIDLEAF INNER JOIN
                         dbo.GXITEM ON dbo.GXITEMCATEGORY.GXITEMID = dbo.GXITEM.GXID INNER JOIN
                         dbo.GXMASTERCAT ON dbo.GXITEMCATEGORY.GXMSCTIDLEAF = dbo.GXMASTERCAT.GXID
WHERE        (dbo.GXMASTERCAT.GXDESCRIPTION LIKE '%Πωλή%')

GROUP BY dbo.GXITEM.GXCODE, dbo.GXMASTERCAT.GXDESCRIPTION

delete Z_ITEM_EAN13_tbl
insert into Z_ITEM_EAN13_tbl
SELECT        
dbo.GXITEMALTERCODE.GXITEMID, 
dbo.GXITEMALTERCODE.GXCODE,dbo.GXITEMALTERCODE.GXID ALTERCODEID
FROM            dbo.GXITEMALTERCODE LEFT OUTER JOIN
                         dbo.GXITEMALTERCODETYPE ON dbo.GXITEMALTERCODE.GXIACTID = dbo.GXITEMALTERCODETYPE.GXID
WHERE        (dbo.GXITEMALTERCODE.GXIACTID = '2197249A-EA4F-4DD1-A58A-0F825D26F473') and dbo.GXITEMALTERCODE .GXACTIVE = 1 
GO



delete z_eidi_b2b_anamenomena_tbl
insert into z_eidi_b2b_anamenomena_tbl
SELECT 
GXITEMCOMPANYPROP.GXITEMID itemid,
sum(GXCOMMERCENTRYLINES.GXAQTY - isnull(GXCOMMERCENTRYLINES.gxTransfQtyLN,0) )anamenomena,
min(GXCOMMERCENTRYLINES.gxExecutionDate) execdate

FROM 
GXTRADEENTRY
INNER JOIN GXCOMMERCIALENTRY ON GXCOMMERCIALENTRY.GXTENTID = GXTRADEENTRY.GXID
INNER JOIN GXCOMMERCENTRYLINES ON GXCOMMERCENTRYLINES.GXCENTID = GXCOMMERCIALENTRY.GXID
INNER JOIN GXCOMMENTRYTYPE ON GXCOMMENTRYTYPE.GXID = GXCOMMERCIALENTRY.GXCOETID
INNER JOIN GXFISCALYEAR ON GXFISCALYEAR.GXID = GXTRADEENTRY.GXFSYRID
INNER JOIN GXITEMCOMPANYPROP ON   GXITEMCOMPANYPROP.GXID = GXCOMMERCENTRYLINES.GXITCPID

WHERE GXTRADEENTRY.GXORIGIN = 4 
AND GXCOMMENTRYTYPE.GXCODE = '1001'
AND GXFISCALYEAR.GXCODE > year(getdate()) - 1 
and GXCOMMERCENTRYLINES.GXAQTY - isnull(GXCOMMERCENTRYLINES.gxTransfQtyLN,0) <> 0 
and GXTRADEENTRY.GXBOOLEANFIELD4 = 1 

group by GXITEMCOMPANYPROP.GXITEMID ,
GXITEMCOMPANYPROP.GXCODE,
GXITEMCOMPANYPROP.GXDESCRIPTION

GO



DELETE [dbo].[Z_ITEM_ATTRIB_FARDOS_TBL]
INSERT INTO [dbo].[Z_ITEM_ATTRIB_FARDOS_TBL] (ENTITYCODE,ENTITYDESCR,ATTRVALUE)
SELECT     dbo.GXITEM.GXCODE AS ENTITYCODE, dbo.GXITEM.GXDESCRIPTION AS ENTITYDESCR, 
                      LTRIM(RTRIM(CASE GXATTRIBUTE.GXATTRIBUTEKIND WHEN 1 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 2 THEN CAST(GXITEMATTRIBUTE.GXFLDDECIMAL AS CHAR(255)) WHEN 3 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 4 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) WHEN 5 THEN CAST(GXITEMATTRIBUTE.GXFLDDATETIME AS CHAR(255)) 
                      WHEN 6 THEN CAST(GXITEMATTRIBUTE.GXFLDBOOLEAN AS CHAR(255)) WHEN 7 THEN CAST
                          ((SELECT     GXDESCRIPTION
                              FROM         GXATTRIBUTELOOKUP
                              WHERE     GXATTRIBUTELOOKUP.GXID = GXITEMATTRIBUTE.GXFLDATLOID) AS CHAR(255)) END)) AS ATTRVALUE
FROM         dbo.GXITEMATTRIBUTE INNER JOIN
                      dbo.GXITEM ON dbo.GXITEM.GXID = dbo.GXITEMATTRIBUTE.GXITEMID INNER JOIN
                      dbo.GXATTRIBUTE ON dbo.GXATTRIBUTE.GXID = dbo.GXITEMATTRIBUTE.GXATTRID INNER JOIN
                      dbo.GXATTRGRPASSIGNMENT ON dbo.GXATTRGRPASSIGNMENT.GXATTGID = dbo.GXITEMATTRIBUTE.GXATTGID AND 
                      dbo.GXATTRGRPASSIGNMENT.GXATTRID = dbo.GXITEMATTRIBUTE.GXATTRID
WHERE     (dbo.GXATTRIBUTE.GXDESCRIPTION = N'ΦΑΡΔΟΣ')

GO

DELETE [dbo].[Z_ITEM_ATTRIB_SEIRA_TBL]
INSERT INTO [dbo].[Z_ITEM_ATTRIB_SEIRA_TBL] (ENTITYCODE,ENTITYDESCR,ATTRVALUE)

SELECT     dbo.GXITEM.GXCODE AS ENTITYCODE, dbo.GXITEM.GXDESCRIPTION AS ENTITYDESCR, 
                      LTRIM(RTRIM(CASE GXATTRIBUTE.GXATTRIBUTEKIND WHEN 1 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 2 THEN CAST(GXITEMATTRIBUTE.GXFLDDECIMAL AS CHAR(255)) WHEN 3 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 4 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) WHEN 5 THEN CAST(GXITEMATTRIBUTE.GXFLDDATETIME AS CHAR(255)) 
                      WHEN 6 THEN CAST(GXITEMATTRIBUTE.GXFLDBOOLEAN AS CHAR(255)) WHEN 7 THEN CAST
                          ((SELECT     GXDESCRIPTION
                              FROM         GXATTRIBUTELOOKUP
                              WHERE     GXATTRIBUTELOOKUP.GXID = GXITEMATTRIBUTE.GXFLDATLOID) AS CHAR(255)) END)) AS ATTRVALUE
FROM         dbo.GXITEMATTRIBUTE INNER JOIN
                      dbo.GXITEM ON dbo.GXITEM.GXID = dbo.GXITEMATTRIBUTE.GXITEMID INNER JOIN
                      dbo.GXATTRIBUTE ON dbo.GXATTRIBUTE.GXID = dbo.GXITEMATTRIBUTE.GXATTRID INNER JOIN
                      dbo.GXATTRGRPASSIGNMENT ON dbo.GXATTRGRPASSIGNMENT.GXATTGID = dbo.GXITEMATTRIBUTE.GXATTGID AND 
                      dbo.GXATTRGRPASSIGNMENT.GXATTRID = dbo.GXITEMATTRIBUTE.GXATTRID
WHERE     (dbo.GXATTRIBUTE.GXDESCRIPTION = N'ΣΕΙΡΑ')

GO


DELETE [dbo].[Z_ITEM_ATTRIB_ZANTA_TBL] 
INSERT INTO [dbo].[Z_ITEM_ATTRIB_ZANTA_TBL] (ENTITYCODE,ENTITYDESCR,ATTRVALUE)

SELECT     dbo.GXITEM.GXCODE AS ENTITYCODE, dbo.GXITEM.GXDESCRIPTION AS ENTITYDESCR, 
                      LTRIM(RTRIM(CASE GXATTRIBUTE.GXATTRIBUTEKIND WHEN 1 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 2 THEN CAST(GXITEMATTRIBUTE.GXFLDDECIMAL AS CHAR(255)) WHEN 3 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 4 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) WHEN 5 THEN CAST(GXITEMATTRIBUTE.GXFLDDATETIME AS CHAR(255)) 
                      WHEN 6 THEN CAST(GXITEMATTRIBUTE.GXFLDBOOLEAN AS CHAR(255)) WHEN 7 THEN CAST
                          ((SELECT     replace(GXDESCRIPTION,' ','')
                              FROM         GXATTRIBUTELOOKUP
                              WHERE     GXATTRIBUTELOOKUP.GXID = GXITEMATTRIBUTE.GXFLDATLOID) AS CHAR(255)) END)) AS ATTRVALUE
FROM         dbo.GXITEMATTRIBUTE INNER JOIN
                      dbo.GXITEM ON dbo.GXITEM.GXID = dbo.GXITEMATTRIBUTE.GXITEMID 
					  inner join GXITEMCOMPANYPROP on GXITEMCOMPANYPROP.GXITEMID = GXITEM.GXID
					  INNER JOIN
                      dbo.GXATTRIBUTE ON dbo.GXATTRIBUTE.GXID = dbo.GXITEMATTRIBUTE.GXATTRID INNER JOIN
                      dbo.GXATTRGRPASSIGNMENT ON dbo.GXATTRGRPASSIGNMENT.GXATTGID = dbo.GXITEMATTRIBUTE.GXATTGID AND 
                      dbo.GXATTRGRPASSIGNMENT.GXATTRID = dbo.GXITEMATTRIBUTE.GXATTRID
WHERE     (dbo.GXATTRIBUTE.GXDESCRIPTION = N'ΖΑΝΤΑ') and GXITEMCOMPANYPROP.GXACTIVE = 1 
and gxitem.GXBOOLEANFIELD1 = 1 

------------ZANTA SEARCH 
DELETE Z_ITEM_ATTRIB_ZANTA_TBL2
INSERT INTO Z_ITEM_ATTRIB_ZANTA_TBL2
SELECT 
Z_ITEM_ATTRIB_ZANTA_TBL.ENTITYCODE,
Z_ITEM_ATTRIB_ZANTA_TBL.ENTITYDESCR,
Z_ITEM_ATTRIB_ZANTA_TBL.ATTRVALUE
FROM
Z_ITEM_ATTRIB_ZANTA_TBL
INNER JOIN Z_ITEM_ATTRIB_GROUP_TBL ON Z_ITEM_ATTRIB_GROUP_TBL.CODE = Z_ITEM_ATTRIB_ZANTA_TBL.ENTITYCODE
INNER JOIN  Z_ITEM_DIKAMAS_b2b_tbl ON Z_ITEM_DIKAMAS_b2b_tbl.GXITEMID = Z_ITEM_ATTRIB_GROUP_TBL.ID
WHERE Z_ITEM_ATTRIB_GROUP_TBL.ATTID IN('38D35BB8-7639-409E-9A18-977CA43B0179','B4918602-98EE-4385-AD7C-6DCB2F623A01','D0402702-D74B-4746-8938-022F7A197418')



---create table z_item_Attrib_dytrader_tbl (itemid uniqueidentifier,itemcode varchar(50),itemdescr varchar(100),kastaskevastis varchar(50),kataskevastisid uniqueidentifier,groupdescr varchar(50),groupid uniqueidentifier,epoxikotita varchar(50),epoxikotitaid uniqueidentifier,GXBOOLEANFIELD1 int,GXACTIVE int,GXWHOLESALEPRICE numeric(12,2))
delete z_item_Attrib_dytrader_tbl
insert into z_item_Attrib_dytrader_tbl
select gxitem.gxid itemid,
gxitem.GXCODE itemcode,
gxitem.GXDESCRIPTION itemdescr,
Z_ITEM_ATTRIB_KATASKEVASTIS.ATTRVALUE kastaskevastis,
Z_ITEM_ATTRIB_KATASKEVASTIS.GXFLDATLOID kataskevastisid,
GXATTRIBUTEGROUP.GXDESCRIPTION groupdescr,
GXATTRIBUTEGROUP.GXID groupid,
Z_ITEM_ATTRIB_EPOXIKOTITA.ATTRVALUE epoxikotita,
Z_ITEM_ATTRIB_EPOXIKOTITA.GXFLDATLOID epoxikotitaid,
gxitem.GXBOOLEANFIELD1,
GXITEMCOMPANYPROP.GXACTIVE,
GXITEMCOMPANYPROP.GXWHOLESALEPRICE
from 
gxitem
inner join GXITEMCOMPANYPROP on GXITEMCOMPANYPROP.GXITEMID = gxitem.GXID
inner join Z_ITEM_ATTRIB_KATASKEVASTIS on Z_ITEM_ATTRIB_KATASKEVASTIS.itemid = gxitem.gxid
left join GXATTRIBUTEGROUP on GXATTRIBUTEGROUP.GXID = gxitem.GXATTGID
left join Z_ITEM_ATTRIB_EPOXIKOTITA on Z_ITEM_ATTRIB_EPOXIKOTITA.ENTITYCODE = gxitem.GXCODE

where 

gxitem.GXBOOLEANFIELD1 = 1 and 
GXITEMCOMPANYPROP.GXACTIVE =1 and 
GXITEMCOMPANYPROP.GXWHOLESALEPRICE > 0

DELETE [dbo].[Z_ITEM_ATTRIB_TAXITITA_TBL] 
INSERT INTO [dbo].[Z_ITEM_ATTRIB_TAXITITA_TBL] (ENTITYCODE,ENTITYDESCR,ATTRVALUE)

SELECT     dbo.GXITEM.GXCODE AS ENTITYCODE, dbo.GXITEM.GXDESCRIPTION AS ENTITYDESCR, 
                      LTRIM(RTRIM(CASE GXATTRIBUTE.GXATTRIBUTEKIND WHEN 1 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 2 THEN CAST(GXITEMATTRIBUTE.GXFLDDECIMAL AS CHAR(255)) WHEN 3 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 4 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) WHEN 5 THEN CAST(GXITEMATTRIBUTE.GXFLDDATETIME AS CHAR(255)) 
                      WHEN 6 THEN CAST(GXITEMATTRIBUTE.GXFLDBOOLEAN AS CHAR(255)) WHEN 7 THEN CAST
                          ((SELECT     GXDESCRIPTION
                              FROM         GXATTRIBUTELOOKUP
                              WHERE     GXATTRIBUTELOOKUP.GXID = GXITEMATTRIBUTE.GXFLDATLOID) AS CHAR(255)) END)) AS ATTRVALUE
FROM         dbo.GXITEMATTRIBUTE INNER JOIN
                      dbo.GXITEM ON dbo.GXITEM.GXID = dbo.GXITEMATTRIBUTE.GXITEMID INNER JOIN
                      dbo.GXATTRIBUTE ON dbo.GXATTRIBUTE.GXID = dbo.GXITEMATTRIBUTE.GXATTRID INNER JOIN
                      dbo.GXATTRGRPASSIGNMENT ON dbo.GXATTRGRPASSIGNMENT.GXATTGID = dbo.GXITEMATTRIBUTE.GXATTGID AND 
                      dbo.GXATTRGRPASSIGNMENT.GXATTRID = dbo.GXITEMATTRIBUTE.GXATTRID
WHERE     (dbo.GXATTRIBUTE.GXDESCRIPTION = N'ΔΕΙΚΤΗΣ ΤΑΧΥΤΗΤΑΣ')

GO

DELETE [dbo].[Z_ITEM_ATTRIB_FORTIOU_TBL] 
INSERT INTO [dbo].[Z_ITEM_ATTRIB_FORTIOU_TBL] (ENTITYCODE,ENTITYDESCR,ATTRVALUE)

SELECT     dbo.GXITEM.GXCODE AS ENTITYCODE, dbo.GXITEM.GXDESCRIPTION AS ENTITYDESCR, 
                      LTRIM(RTRIM(CASE GXATTRIBUTE.GXATTRIBUTEKIND WHEN 1 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 2 THEN CAST(GXITEMATTRIBUTE.GXFLDDECIMAL AS CHAR(255)) WHEN 3 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 4 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) WHEN 5 THEN CAST(GXITEMATTRIBUTE.GXFLDDATETIME AS CHAR(255)) 
                      WHEN 6 THEN CAST(GXITEMATTRIBUTE.GXFLDBOOLEAN AS CHAR(255)) WHEN 7 THEN CAST
                          ((SELECT     GXDESCRIPTION
                              FROM         GXATTRIBUTELOOKUP
                              WHERE     GXATTRIBUTELOOKUP.GXID = GXITEMATTRIBUTE.GXFLDATLOID) AS CHAR(255)) END)) AS ATTRVALUE
FROM         dbo.GXITEMATTRIBUTE INNER JOIN
                      dbo.GXITEM ON dbo.GXITEM.GXID = dbo.GXITEMATTRIBUTE.GXITEMID INNER JOIN
                      dbo.GXATTRIBUTE ON dbo.GXATTRIBUTE.GXID = dbo.GXITEMATTRIBUTE.GXATTRID INNER JOIN
                      dbo.GXATTRGRPASSIGNMENT ON dbo.GXATTRGRPASSIGNMENT.GXATTGID = dbo.GXITEMATTRIBUTE.GXATTGID AND 
                      dbo.GXATTRGRPASSIGNMENT.GXATTRID = dbo.GXITEMATTRIBUTE.GXATTRID
WHERE     (dbo.GXATTRIBUTE.GXDESCRIPTION = N'ΔΕΙΚΤΗΣ ΦΟΡΤΙΟΥ')

DELETE [dbo].[Z_ITEM_ATTRIB_pelma_TBL]
INSERT INTO [dbo].[Z_ITEM_ATTRIB_pelma_TBL] (ENTITYCODE,ENTITYDESCR,ATTRVALUE)
SELECT     dbo.GXITEM.GXCODE AS ENTITYCODE, dbo.GXITEM.GXDESCRIPTION AS ENTITYDESCR, 
                      LTRIM(RTRIM(CASE GXATTRIBUTE.GXATTRIBUTEKIND WHEN 1 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 2 THEN CAST(GXITEMATTRIBUTE.GXFLDDECIMAL AS CHAR(255)) WHEN 3 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) 
                      WHEN 4 THEN CAST(GXITEMATTRIBUTE.GXFLDSTRING AS CHAR(255)) WHEN 5 THEN CAST(GXITEMATTRIBUTE.GXFLDDATETIME AS CHAR(255)) 
                      WHEN 6 THEN CAST(GXITEMATTRIBUTE.GXFLDBOOLEAN AS CHAR(255)) WHEN 7 THEN CAST
                          ((SELECT     GXDESCRIPTION
                              FROM         GXATTRIBUTELOOKUP
                              WHERE     GXATTRIBUTELOOKUP.GXID = GXITEMATTRIBUTE.GXFLDATLOID) AS CHAR(255)) END)) AS ATTRVALUE
FROM         dbo.GXITEMATTRIBUTE INNER JOIN
                      dbo.GXITEM ON dbo.GXITEM.GXID = dbo.GXITEMATTRIBUTE.GXITEMID INNER JOIN
                      dbo.GXATTRIBUTE ON dbo.GXATTRIBUTE.GXID = dbo.GXITEMATTRIBUTE.GXATTRID INNER JOIN
                      dbo.GXATTRGRPASSIGNMENT ON dbo.GXATTRGRPASSIGNMENT.GXATTGID = dbo.GXITEMATTRIBUTE.GXATTGID AND 
                      dbo.GXATTRGRPASSIGNMENT.GXATTRID = dbo.GXITEMATTRIBUTE.GXATTRID
WHERE     (dbo.GXATTRIBUTE.GXDESCRIPTION = N'ΠΕΛΜΑ')
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
