select 
CONCAT(
'UPDATE DYGXTRADER2 SET DYGXTRADER2.DYYN = 0 WHERE DYGXTRADER2.DYID = ',
CHAR(39),
DYGXTRADER2.DYID,
CHAR(39)),
DYGXTRADER2.DYID,
DYGXTRADER2.DYYN,
DYGXTRADER2.GXTRADERID,
DYGXTRADER2.DYGXTRADER2_FIELD4,
DYGXTRADER2.DYGXTRADER2_FIELD5,
DYGXTRADER2.DYGXTRADER2_FIELD6
from DYGXTRADER2
inner join GXATTRIBUTELOOKUP on GXATTRIBUTELOOKUP.GXID = DYGXTRADER2.DYGXTRADER2_FIELD4
inner join GXATTRIBUTEGROUP on GXATTRIBUTEGROUP.GXID = DYGXTRADER2.DYGXTRADER2_FIELD5
where GXTRADERID = (select gxid from GXTRADER where gxtin = '800627321')
and
--(GXATTRIBUTELOOKUP.GXDESCRIPTION IN ('MICHELIN','BFGOODRICH','KORMORAN','UNIROYAL'))

--(GXATTRIBUTELOOKUP.GXDESCRIPTION IN ('CONTINENTAL','UNIROYAL','VIKING','BARUM','GENERAL TYRE'))

--(GXATTRIBUTELOOKUP.GXDESCRIPTION IN ('BRIDGESTONE','FIRESTONE','LASSA','UNIROYAL','DAYTON'))

--(GXATTRIBUTELOOKUP.GXDESCRIPTION IN ('GOODYEAR','SAVA','DUNLOP','DEBICA','COOPER'))
